// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqhalfpkhkxggtbpxaxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxaGFsZnBraGt4Z2d0YnB4YXh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMzA4OTMsImV4cCI6MjA2NTcwNjg5M30.Fo-bdBXmH6l0rSoPISGMrlA8IMcwH-8-IwujdrPZ97I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);